namespace: dev
app: be-tcf

datadog:
  env: dev
  service: be-tcf

deployment:
  name: be-tcf-deployment
  replicas: 2

image:
  repository: ghcr.io/utikpuhlik/be-tcf
  pullPolicy: Always
  tag: latest

service:
  type: ClusterIP
  name: be-tcf-svc
  port: 8080

resources:
  requests:
    memory: '384Mi'
    cpu: '100m'
  limits:
    memory: '512Mi'
    cpu: '150m'

secrets:
  api_utils: api-utils-secret
  app_secrets: be-tcf-secret

imagePullSecrets:
  name: ghcr-secret

ingress:
  enabled: true
  name: be-tcf-ingressroute
  className: traefik
  host: api-dev.eucalytics.uk
  pathPrefix: /tcf
  annotations: { }
